apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-01-19T16:23:16Z"
  generation: 29
  labels:
    app: user-management
  name: user-management
  namespace: default
  resourceVersion: "2318433"
  selfLink: /apis/apps/v1/namespaces/default/deployments/user-management
  uid: ff5dddce-3ad7-11ea-9bb7-42010a8400a8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-management
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-management
    spec:
      containers:
      - env:
        - name: FLASK_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: FLASK_SECRET_KEY
              name: user-management-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: user-management-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: user-management-config
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: user-management-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: user-management-config
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: user-management-config
        - name: POSTGRES_INITIALIZE
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_INITIALIZE
              name: user-management-config
        - name: CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              key: CONSUL_HOST
              name: user-management-config
        - name: CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              key: CONSUL_PORT
              name: user-management-config
        image: registry.hub.docker.com/slosquad42/user_management:latest
        imagePullPolicy: Always
        name: user-management
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-19T16:23:16Z"
    lastUpdateTime: "2020-01-19T23:21:42Z"
    message: ReplicaSet "user-management-79f75d59d5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-20T01:55:21Z"
    lastUpdateTime: "2020-01-20T01:55:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 29
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
